# -*- coding: utf-8 -*-
"""PKL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S0BYRvBtfWgt6u21es6eURwa6cxgf3Kh
"""

import joblib
import os
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
import streamlit as st
# Install streamlit if not already installed and then import it

    


# Define model filename
model_filename = "iris_model.pkl"

# Check if model exists, if not, train and save it
if not os.path.exists(model_filename):
    print(f"Model file '{model_filename}' not found. Training and saving a new model.")
    # Load the Iris dataset
    iris = load_iris()
    X, y = iris.data, iris.target

    # Train a simple Logistic Regression model
    model_to_save = LogisticRegression(max_iter=1000)
    model_to_save.fit(X, y)

    # Save the trained model
    joblib.dump(model_to_save, model_filename)
    print(f"Iris model trained and saved as '{model_filename}'")
else:
    print(f"Model file '{model_filename}' found. Loading existing model.")

# Load the trained model
model = joblib.load(model_filename)

st.title("🌸 Iris Flower Prediction")

st.write("Enter the flower measurements:")

sepal_length = st.number_input("Sepal Length", min_value=0.0)
sepal_width = st.number_input("Sepal Width", min_value=0.0)
petal_length = st.number_input("Petal Length", min_value=0.0)
petal_width = st.number_input("Petal Width", min_value=0.0)

if st.button("Predict"):

    prediction = model.predict([[
        sepal_length,
        sepal_width,
        petal_length,
        petal_width
    ]])

    flower_names = [
        "Setosa",
        "Versicolor",
        "Virginica"
    ]

    st.success(f"The predicted flower is: {flower_names[prediction[0]]}")

# Train and save a simple Iris classification model
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
import joblib

# Load the Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Train a simple Logistic Regression model
model = LogisticRegression(max_iter=1000)
model.fit(X, y)

# Save the trained model
joblib.dump(model, 'iris_model.pkl')

print("Iris model trained and saved as 'iris_model.pkl'")

